up:
	docker-compose -f ./docker/docker-compose.yml up -d --build --force-recreate

down:
	docker-compose -f ./docker/docker-compose.yml down

sh:
	docker exec -it shoponpon_web sh

serve:
	docker exec -it shoponpon_web sh -c 'yarn serve'

